name: Registry App CI

on:
  push:
    branches : [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: ./gradlew build
      - name: test
        run: ./gradlew test
